const POSTS = {
  LOAD: 'POSTS_LOAD',
  LOAD_SUCCESS: 'POSTS_LOAD_SUCCESS',
  LOAD_FAIL: 'POSTS_LOAD_FAIL',
  SELECT: 'POSTS_SELECT',
  CLEAR: 'POSTS_CLEAR',
  SET_USERS: 'POSTS_SET_USERS',
};

const PHOTOS = {
  LOAD: 'PHOTOS_LOAD',
  LOAD_SUCCESS: 'PHOTOS_LOAD_SUCCESS',
  LOAD_FAIL: 'PHOTOS_LOAD_FAIL',
};

const BASE_URL = 'https://jsonplaceholder.typicode.com';

export { POSTS, PHOTOS, BASE_URL };
